# Путь для скачивания
download_path: dl
# Моды
mods:
  # Можно записать ссылку...
  - https://steamcommunity.com/sharedfiles/filedetails/?id=2266952591
  # Или же просто id
  - 2266952591  # -------------------------------------------- ^
