name: release

# Запускать только при назначении тега вручную
on: push

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry export -f requirements.txt -o requirements.txt --dev
          pip install -r requirements.txt
          pip install py2exe
      - name: Test with pytest
        run: |
          pytest
      - name: Build Application
        # Запускать, если указан тег
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          python setup.py py2exe
          python make.py
      - name: Generate Changelog
        # Запускать, если указан тег
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          python gen_changelog.py $GITHUB_REF
      - name: Release
        # Запускать, если указан тег
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v1
        with:
          # name: ... # Name of the release. defaults to tag name
          body_path: CHANGELOG.md
          files: steam-workshop-downloader.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
